resources:
- manager.yaml

generatorOptions:
  disableNameSuffixHash: true

secretGenerator:
  - name: vcloud-basic-auth
    literals:
      - username=${VCD_USERNAME_B64} # VCD username to initialize the CAPVCD. If system administrator is the user, please use 'system/administrator' as the username.
      - password=${VCD_PASSWORD_B64} # Password

configMapGenerator:
- files:
  - controller_manager_config.yaml
  name: manager-config
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
